---
title: "Starkregenereignisse in Deutschland"
author: "Sarah Jane Eckhardt, Patrizia Kastalski"
format: html
editor: visual
---

## Bibliotheken

```{r}
#| echo: false
#| message: false
library(sf)
library(giscoR)
library(lubridate)
library(patchwork)
library(tidyverse)
library(rdwd)
library(RCurl)
library(knitr)
```

Zeigt alle wichtigen Bibliotheken für die Programmierung.

## URLs der herunterzuladenden Regendaten

Auswahl von Datensätzen vom DWD-Server

```{r}
links <- selectDWD(res = "daily",  var = "more_precip", per = "hist", current=TRUE)
length(links)
```

## Datenauswahl nur relevante Daten von [**2014-2016**]{.underline} **!!!**

```         
```

## Daten herrunterladen

```{r}
#localfiles <- dataDWD(links[1:3], joinbf=TRUE, sleep=0.2, read=FALSE)
```

```{r}
d <- selectDWD(name = "Bochum", res = "daily", var = "kl", per = "historical", current=TRUE) |>
  dataDWD(read = FALSE) |>
  readDWD(varnames = TRUE) |>
  mutate(datum = ymd(MESS_DATUM))
ggplot(data = d) + geom_col(mapping = aes(x = datum, y = RSK.Niederschlagshoehe))
```
